apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - env:
        - name: GREETING_PREFIX
          valueFrom:
            configMapKeyRef:
              name: spring-boot-configmaps-demo
              key: greeter.prefix
