FROM registry.redhat.io/openjdk/openjdk-8-rhel8

MAINTAINER Shah Zobair
#COPY initial/target/serving-web-content-initial-0.0.1-SNAPSHOT.jar /
COPY serving-web-content-initial-0.0.1-SNAPSHOT.jar /
ENTRYPOINT ["java","-jar","/serving-web-content-initial-0.0.1-SNAPSHOT.jar"]
